### ISSUE TITLE
[Request] Actions 버전 업데이트

### ISSUE THREAD

**Issue by marshallku** [algorimon/git-ster#3]
### Problem

https://github.com/algorimon/git-ster/blob/main/.github/workflows/build.yml#L12-L19

deprecated된 actions를 사용하고 있습니다.

### Solution

`actions/checkout`의 버전을 v2 -> v3으로
`actions/setup-node`의 버전을 v2 -> v3으로 수정합니다

### Further suggestions

https://github.com/marshallku/cookies-next/tree/master/.github/workflows

간단하게 참고할 수 있는 workflow들 예제 첨부합니다.

**Comment by puk0806** [comment]
감사합니다!
